/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsFrayeoDigitalLiteracyRouteImport } from './routes/projects.frayeo-digital-literacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFrayeoDigitalLiteracyRoute =
  ProjectsFrayeoDigitalLiteracyRouteImport.update({
    id: '/projects/frayeo-digital-literacy',
    path: '/projects/frayeo-digital-literacy',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/frayeo-digital-literacy': typeof ProjectsFrayeoDigitalLiteracyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/frayeo-digital-literacy': typeof ProjectsFrayeoDigitalLiteracyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/frayeo-digital-literacy': typeof ProjectsFrayeoDigitalLiteracyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/frayeo-digital-literacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/frayeo-digital-literacy'
  id: '__root__' | '/' | '/projects/frayeo-digital-literacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsFrayeoDigitalLiteracyRoute: typeof ProjectsFrayeoDigitalLiteracyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/frayeo-digital-literacy': {
      id: '/projects/frayeo-digital-literacy'
      path: '/projects/frayeo-digital-literacy'
      fullPath: '/projects/frayeo-digital-literacy'
      preLoaderRoute: typeof ProjectsFrayeoDigitalLiteracyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsFrayeoDigitalLiteracyRoute: ProjectsFrayeoDigitalLiteracyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
