/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadershipAisRouteImport } from './routes/leadership.ais'
import { Route as ProjectsCollegeBudgetingSystemRouteImport } from './routes/projects.college-budgeting-system'
import { Route as ProjectsDatakingSecurityAssessmentRouteImport } from './routes/projects.dataking-security-assessment'
import { Route as ProjectsFrayeoDigitalLiteracyRouteImport } from './routes/projects.frayeo-digital-literacy'
import { Route as ProjectsMedicalDeviceRiskAssessmentRouteImport } from './routes/projects.medical-device-risk-assessment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipAisRoute = LeadershipAisRouteImport.update({
  id: '/leadership/ais',
  path: '/leadership/ais',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCollegeBudgetingSystemRoute =
  ProjectsCollegeBudgetingSystemRouteImport.update({
    id: '/projects/college-budgeting-system',
    path: '/projects/college-budgeting-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsDatakingSecurityAssessmentRoute =
  ProjectsDatakingSecurityAssessmentRouteImport.update({
    id: '/projects/dataking-security-assessment',
    path: '/projects/dataking-security-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsFrayeoDigitalLiteracyRoute =
  ProjectsFrayeoDigitalLiteracyRouteImport.update({
    id: '/projects/frayeo-digital-literacy',
    path: '/projects/frayeo-digital-literacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsMedicalDeviceRiskAssessmentRoute =
  ProjectsMedicalDeviceRiskAssessmentRouteImport.update({
    id: '/projects/medical-device-risk-assessment',
    path: '/projects/medical-device-risk-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leadership/ais': typeof LeadershipAisRoute
  '/projects/college-budgeting-system': typeof ProjectsCollegeBudgetingSystemRoute
  '/projects/dataking-security-assessment': typeof ProjectsDatakingSecurityAssessmentRoute
  '/projects/frayeo-digital-literacy': typeof ProjectsFrayeoDigitalLiteracyRoute
  '/projects/medical-device-risk-assessment': typeof ProjectsMedicalDeviceRiskAssessmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leadership/ais': typeof LeadershipAisRoute
  '/projects/college-budgeting-system': typeof ProjectsCollegeBudgetingSystemRoute
  '/projects/dataking-security-assessment': typeof ProjectsDatakingSecurityAssessmentRoute
  '/projects/frayeo-digital-literacy': typeof ProjectsFrayeoDigitalLiteracyRoute
  '/projects/medical-device-risk-assessment': typeof ProjectsMedicalDeviceRiskAssessmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leadership/ais': typeof LeadershipAisRoute
  '/projects/college-budgeting-system': typeof ProjectsCollegeBudgetingSystemRoute
  '/projects/dataking-security-assessment': typeof ProjectsDatakingSecurityAssessmentRoute
  '/projects/frayeo-digital-literacy': typeof ProjectsFrayeoDigitalLiteracyRoute
  '/projects/medical-device-risk-assessment': typeof ProjectsMedicalDeviceRiskAssessmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leadership/ais'
    | '/projects/college-budgeting-system'
    | '/projects/dataking-security-assessment'
    | '/projects/frayeo-digital-literacy'
    | '/projects/medical-device-risk-assessment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leadership/ais'
    | '/projects/college-budgeting-system'
    | '/projects/dataking-security-assessment'
    | '/projects/frayeo-digital-literacy'
    | '/projects/medical-device-risk-assessment'
  id:
    | '__root__'
    | '/'
    | '/leadership/ais'
    | '/projects/college-budgeting-system'
    | '/projects/dataking-security-assessment'
    | '/projects/frayeo-digital-literacy'
    | '/projects/medical-device-risk-assessment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadershipAisRoute: typeof LeadershipAisRoute
  ProjectsCollegeBudgetingSystemRoute: typeof ProjectsCollegeBudgetingSystemRoute
  ProjectsDatakingSecurityAssessmentRoute: typeof ProjectsDatakingSecurityAssessmentRoute
  ProjectsFrayeoDigitalLiteracyRoute: typeof ProjectsFrayeoDigitalLiteracyRoute
  ProjectsMedicalDeviceRiskAssessmentRoute: typeof ProjectsMedicalDeviceRiskAssessmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership/ais': {
      id: '/leadership/ais'
      path: '/leadership/ais'
      fullPath: '/leadership/ais'
      preLoaderRoute: typeof LeadershipAisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/college-budgeting-system': {
      id: '/projects/college-budgeting-system'
      path: '/projects/college-budgeting-system'
      fullPath: '/projects/college-budgeting-system'
      preLoaderRoute: typeof ProjectsCollegeBudgetingSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/dataking-security-assessment': {
      id: '/projects/dataking-security-assessment'
      path: '/projects/dataking-security-assessment'
      fullPath: '/projects/dataking-security-assessment'
      preLoaderRoute: typeof ProjectsDatakingSecurityAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/frayeo-digital-literacy': {
      id: '/projects/frayeo-digital-literacy'
      path: '/projects/frayeo-digital-literacy'
      fullPath: '/projects/frayeo-digital-literacy'
      preLoaderRoute: typeof ProjectsFrayeoDigitalLiteracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/medical-device-risk-assessment': {
      id: '/projects/medical-device-risk-assessment'
      path: '/projects/medical-device-risk-assessment'
      fullPath: '/projects/medical-device-risk-assessment'
      preLoaderRoute: typeof ProjectsMedicalDeviceRiskAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadershipAisRoute: LeadershipAisRoute,
  ProjectsCollegeBudgetingSystemRoute: ProjectsCollegeBudgetingSystemRoute,
  ProjectsDatakingSecurityAssessmentRoute:
    ProjectsDatakingSecurityAssessmentRoute,
  ProjectsFrayeoDigitalLiteracyRoute: ProjectsFrayeoDigitalLiteracyRoute,
  ProjectsMedicalDeviceRiskAssessmentRoute:
    ProjectsMedicalDeviceRiskAssessmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
